// client/src/game/tugofwar/paragraphs.js
const tugOfWarParagraphs = [
    "The ancient library's vaulted ceilings cast shadows across rows of tomes bound in cracked leather and faded cloth, each whispering echoes of generations past. Dust motes drifted in thin beams of afternoon light, settling on edges of pages that, once opened, revealed yellowed margins, delicate script, and occasional smudges made by scholars' impatient fingers. Somewhere far off a clock chimed, soft but resolute, reminding the keeper of time's steady march. He paused, fingertip tracing the spine of a manuscript so fragile he hesitated, knowing the effort to open it once might be its undoing. Yet curiosity won: a sigh escaped as the cover lifted, revealing the first line, curled at the corner-as though guarding what lay beyond.",

    "On the windswept beach at dawn, waves lapped quietly over shells and smooth stones while gulls wheeled overhead in stark silhouettes against a pale sky. Each breath of salty air carried the scent of seaweed and wet wood, the tang of brine clinging to skin, the promise of tide pools alive with creatures that only stir when the world is still. She walked along the shoreline, toes sinking into sand that glowed warm and faintly pink in the early sun, picking up a scallop shell here, a strand of kelp there, listening to the rhythmic pulse of ocean meeting land. In that moment the horizon stretched infinite, and she felt both infinitesimal and boundless.",

    "The train rattled through darkness—cool metal bones humming underfoot, windows reflecting ghosts of passing forests, stations unseen. Inside, the carriage lights glowed soft ivory, illuminating travelers in various states of wakefulness: one reading by flashlight, another clutching a travel-worn violin case, children pressed noses against glass to watch lights blur into streaks. Somewhere a conductor's distant voice echoed, muffled by steel and air, calling out destinations no one else could make out clearly. The smell of coffee and old upholstery mingled. At each station the doors hissed, letting echoes of other lives in and out. And through it all the train carried its passengers onward, steadily—through night, toward dawn, toward someplace they could call “arrival.”",

    "High in the mountain pass, where the air thinned and wildflowers dared to bloom between boulders, a hiker paused to catch her breath. The wind tugged at her jacket, cold as glass, blowing wisps of fog that curled around crags, obscuring sheer drops and jagged outlines. She listened: water rushing somewhere below, rocks shifting with the weight of unseen animals, a distant bird's cry. Every inhalation burned, but with the pain came clarity—of space, of solitude, of universe expanding in loud silence. The sun, low in the sky, painted clouds in rods of rose and gold, slicing through mist. She knew the climb had been hard, that every step had demanded more than she thought possible—and yet here, in this liminal space between earth and sky, she felt unbelievably alive.",

    "The marketplace buzzed with life under a sky drenched in the heat of noon. Stalls overflowed with colors: vibrant fabric from distant lands, spice jars bright with paprika and turmeric, fruits glistening as though polished, their juices promising sweet reprieves. Merchants called out their wares—“fresh bread,” “just picked,” “rare silks imported”—each voice competing with children's laughter, donkey brays, the scurry of hooves and feet. Over it all hung the mingled scents: roasting meat, herbs steeped in oil, citrus fruits splitting open in the sun. She pushed through the crowd, letting sights and sounds fill her senses, allowed herself to taste a piece of fruit offered by a vendor, pause at a textile stall to feel the threads under her fingers. Everything was alive, everything was movement, everything insisted on being noticed.",

    "He sat by the window, evening rain drumming lightly against the glass, watching city lights flicker as dusk deepened. Neon signs blinked advertisements in garish fonts, headlights slurry across wet pavement, shadows quivered in the alleys between buildings. Steam curled from manholes; people huddled under umbrellas, jackets pulled high against the chill. Inside the room, the air smelled of old books and pipe smoke. In his hand, a pen hovered over a journal, fingers hesitating before inking thought into permanence. Outside, the city pulsed—relentless, uncontrolled, beautiful in its chaos. And he felt both connected and distant, as though he observed from behind glass watching life unfold just beyond reach.",

    "They planted the oak sapling at sunrise, digging in soil still cool with dew. It wasn't much—just a slender trunk, tender branches that quivered in the breeze, leaves newborn and fragile. But as they stepped back, watering can in hand, the morning sun caught a droplet hanging on the tip of a leaf, like a promise. The sky above was apricot-pink, feathered with clouds, and birds sang in cautious greetings. Behind them, the land rolled in gentle hills, green and fertile, touched by shadows cast from a rising day. In the sapling they saw hope: a future shade, or home for birds, or simply a marker of care. They covered the roots, patting earth, whispering words that perhaps only the wind would carry. And as they left, they turned once more—heart light, believing that small beginnings matter.",

    "The old clock tower stood at the square's center, its face cracked, hands frozen at some long-forgotten hour. Ivy clung to its sides, roots penetrating mortar, tendrils dancing with every drift of wind. Below its bell, cobblestones lay uneven, worn by countless footsteps, stories folded into every fissure. Market stalls once gathered there, children once played, travelers once paused to rest under its shadow. Now, pigeons cooed, vines rustled, and silence ruled where laughter used to ring. Yet there was dignity in the decay: beauty in ruin, poetry in what time had both created and claimed. For some, it was a relic; for others, a repository of memory—every crack a scar of history, every crack a testament.",

    "She opened the window to the garden at dusk and was met with blossoms heavy with scent, air thick with jasmine, honeysuckle, and something richer-soil, rain expected, blossoms made heavy by the day's heat. Fireflies began their dance among stems; petals closed in slow exhalation; insects chirped into the gloom. A single lantern glowed on the porch, casting a golden halo, shadows dancing at its edge. She leaned forward, breath suspended between the warm air and cooling night, tasting moisture, imagining dew forming on leaves. It felt like a threshold: between day and night, between what was seen and what was felt. Inside she held her breath, outside the garden exhaled.",

    "The sea captain's cabin was small and cluttered: map tables strewn with charts, sextant and compass glinting in lantern light, journals filled with salt-stained ink lying open, logs of storms and calm nights side by side. The wood floor creaked with every sway of the vessel; the smell of brine and tar was ever present, mingled with old rope and oiled wood. Outside the porthole, waves slapped rhythmically against the hull, moonlight dancing on swells, turning the sea into a sheet of shifting silver. He sat hunched over, poring over a promising course chart, tracing lines in hopes of safe passage, animating the unknown with each steady stroke of his pen. Above deck the wind moaned; below deck every plank and rivet protested. Still he persisted, guided by stars he could no longer see but trusted all the same."
];


function getRandomParagraph() {
    return tugOfWarParagraphs[Math.floor(Math.random() * tugOfWarParagraphs.length)]
}

export { getRandomParagraph, tugOfWarParagraphs }